### PR TITLE
Submitting "Speedtest Tracker" to Docker Template

### PR DESCRIPTION
**Pull request by ABOhiccups**
Replace "????" with random numbers without mixing up with other Docker Containers.

### CODE REVIEW

**Comment by FixedBit** [comment]
Actually if you can just change it to something random close to the real port numbers that will be fine then I can merge it, thanks!

**Comment by ABOhiccups** [comment]
I give it a number from official document guide. I think you will change 8080 to something different without mixing up with other Docker Compose.

**Comment by ABOhiccups** [comment]
I gave it new port numbers for Speedtest Tracker.

**Review by ABOhiccups — COMMENTED** [review]
I gave it new port numbers for Speedtest Tracker.

**Pull request merged**
